#! /bin/sh

sxhkd &
picom -b -f --experimental-backends &
killall mpd
mpd &
~/.config/polybar/launch.sh
feh --bg-fill ~/poly.jpg
xmodmap ~/.config/X11/xmodmap
killall "flameshot"
flameshot & # screenshot utility
killall "dunst"
dunst & # notification daemon
killall "unclutter"
unclutter & # clean cursor when in idle
killall "greenclip"
greenclip daemon &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Rules
#bspc rule -a firefox desktop='^2' focus=on follow=on

# Truncate a couple of common commands that are used herein.
_bc() {
    bspc config "$@"
}

### BSPWM configuration ###
_bc top_padding 0
_bc bottom_padding 25
_bc border_width 0
_bc window_gap 12
_bc split_ratio 0.52
_bc borderless_monocle true
_bc gapless_monocle true

# Colors
_bc normal_border_color "#c8ccd4"
_bc focused_border_color "#61afef"
